name: test
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  step-a:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1

  step-b:
    if: ${{ github.event.pull_request.merged == true}}
    runs-on: ubuntu-latest
    steps:
      - run: echo stepb is running...
    needs:
      - step-a
